apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: demo
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  #type: ClusterIP  
  type: LoadBalancer
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world
